script: |
  cd /home/malandev/finediamond_app/app

  git pull origin main

  source /home/malandev/virtualenv/finediamond_app/3.12/bin/activate

  pip install -r requirements.txt

  python manage.py migrate --noinput

  python manage.py collectstatic --noinput

  touch /home/malandev/finediamond_app/tmp/restart.txt
  echo "ðŸš€ Deployment Successful!"
